spring.application.name=cinema-api

#CONFIGURACION BASE DE DATOS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}


#CONFIGURACION JWT
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}

springdoc.swagger-ui.operationsSorter=method


##BASE DE DATOS USER pinpon
##BASE DE DATOS PASSWORD pinponalv
##BASE DE DATOS URL jdbc:mysql://localhost:3306/cinema
##PRIVATE KEY 23da59fc1d42c4ba15a6a4c368cc7b226739ecc1db22249bc4403e729613b14f
##USER GENERATOR pinpon
