spring.application.name=cinema-api

#CONFIGURACION BASE DE DATOS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/cinema-api
spring.datasource.username=root
spring.datasource.password=root


#CONFIGURACION JWT
security.jwt.private.key=23da59fc1d42c4ba15a6a4c368cc7b226739ecc1db22249bc4403e729613b14f
security.jwt.user.generator=pinpon

springdoc.swagger-ui.operationsSorter=method